### ISSUE TITLE
registerCollection removed in Sails 10.5

### ISSUE THREAD

**Issue by kdclaw3** [atiertant/sails-oracle#1]
registerCollection has been removed in Sails 10.5 the adapter bombs out with:

![screen shot 2015-01-18 at 12 51 06 pm](https://cloud.githubusercontent.com/assets/6394327/5793416/bcd68592-9f10-11e4-979b-3d5d627e2a32.png)

**Comment by atiertant** [comment]
this function has been revoved for code
