### ISSUE TITLE
adapter status?

### ISSUE THREAD

**Issue by tjwebb** [atiertant/sails-oracle#2]
Is this adapter actively maintained, and is it corporate-backed? Any info would be appreciated, thanks.

**Comment by atiertant** [comment]
hi,this adapter will be use in production environnement for our products and we would like to share it with the sails' community.but it's difficult to integrate some code in waterline-sequel.
maybe we should use knex instead of sequel.

**Comment by tjwebb** [comment]
Yea feel free to use knex underneath. I'm planning to replace the sails-postgresql SQL builder with knex eventually, anyway.

**Comment by aabhushan** [comment]
Are you planning to use the oracle official node library for this? Any updates would be helpful.

**Comment by atiertant** [comment]
@aabhushan yes,our next adapter will use node-oracledb.work is in progress and we are waitting some functions not already implemented in oracle driver.

**Comment by aabhushan** [comment]
Great. Thanks. Do you have a Github repo for that? Any ETA?

**Comment by atiertant** [comment]
as soon as we got something working a bit,couldn't do any ETA because node-oracledb has no ETA... https://github.com/oracle/node-oracledb/issues/4

**Comment by aabhushan** [comment]
Looks like the issue https://github.com/oracle/node-oracledb/issues/4 is closed now. :)

**Comment by atiertant** [comment]
that's rigth, thanks to them ! we are now working on ingrate this in our adapter while they implement lob support(https://github.com/oracle/node-oracledb/issues/19).

**Comment by aabhushan** [comment]
That's great. Looking forward to trying it out. LOB support would be a great addition.

**Comment by aabhushan** [comment]
Any ETAs? :)

**Comment by atiertant** [comment]
maybe one or two months...

**Comment by aabhushan** [comment]
Thanks for letting me know, atiertant!

**Comment by aabhushan** [comment]
Hi Alexandre, Do we have any updates on this?

**Comment by atiertant** [comment]
oracledb support now LOB !
we need it to be integrate in knex to compete our new adapter.

**Comment by atiertant** [comment]
@aabhushan new adapter is in progress : https://github.com/Atlantis-Software/offshore-sql

**Comment by tjwebb** [comment]
We've already built a new one based on the oracle-supported adapter: https://github.com/waterlinejs/oracle-adapter

**Comment by atiertant** [comment]
@tjwebb your adapter is working on our old modified version of sequel ... our new one use knex.

**Comment by tjwebb** [comment]
Does it use the Oracle-supported driver?

**Comment by atiertant** [comment]
yes using this : https://github.com/tgriesser/knex/pull/990
