### ISSUE TITLE
occi.h: No such file or directory

### ISSUE THREAD

**Issue by jhereu** [atiertant/sails-oracle#4]
Hi,

First of all, thank you for keeping this package up to date. Well, even though I have been trying to install it in an Ubuntu Desktop 14.04.1 (x64) OS machine for several days, I have not achieved it yet.

I guess I have already read all possible solutions, but I still get the "fatal error: Occi.h: no such file or directory". Maybe I'm doing something wrong.

First of all, I installed the Oracle Instant Client, as well as the developer and sql extra packages, via alien. I've created the environment variables as INSTALL.md dictates and so on.

So, when it comes to install the package, i run "npm install sails-oracledb" in my sails project root directory, but I still get this annoying message. The env vars are ok and the libclntsh.so and libocci.sh files are also correctly made.

I hope you could throw some light on my case.

Thank you :)

P.S: Im running Sails 0.10.5.

**Comment by atiertant** [comment]
hi,
i think install rpm on ubuntu using alien is not a good way.
you should install basic and sdk package from zip ...

occi.h 's folders is define in OCI_INCLUDE_DIR ,here are default forders for x86_64 platform (replace 'client64' by 'client' on i386)

export OCI_LIB_DIR=/usr/lib/oracle/12.1/client64/lib/
export OCI_INCLUDE_DIR=/usr/include/oracle/12.1/client64/
export OCI_VERSION=12
export ORACLE_HOME=/usr/lib/oracle/12.1/client64

**Comment by jhereu** [comment]
Well, I don't know how, but it worked. I had already set these same enviroment variables hundreds of times before...

Thank you very much :dancer:

**Comment by jhereu** [comment]
I do understand it now. The key is to define the env vars as superuser mode (sudo su) and install the module just after defining them without leaving the superuser session. Just sudo doesn't work to define the vars. 

Thanks!
